-- GROOT VECTOR DATABASE - PARTE 1 (TABELAS)
-- Execute primeiro este bloco

-- 1. Ativar extensão pgvector
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Tabela de embeddings profissionais
CREATE TABLE IF NOT EXISTS knowledge_embeddings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  embedding VECTOR(384), -- HuggingFace dimensions (grátis)
  source TEXT,
  category TEXT,
  language TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabela de bugs e soluções
CREATE TABLE IF NOT EXISTS bugs_knowledge (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  error_message TEXT NOT NULL,
  stack_trace TEXT,
  solution TEXT NOT NULL,
  language TEXT,
  framework TEXT,
  embedding VECTOR(384), -- HuggingFace dimensions
  confidence FLOAT DEFAULT 0.0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Tabela de código aprendido
CREATE TABLE IF NOT EXISTS code_knowledge (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repo_url TEXT,
  file_path TEXT,
  content TEXT NOT NULL,
  language TEXT,
  functions JSONB,
  patterns JSONB,
  embedding VECTOR(384), -- HuggingFace dimensions
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Índices para performance
CREATE INDEX IF NOT EXISTS idx_knowledge_embeddings_vector ON knowledge_embeddings 
USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

CREATE INDEX IF NOT EXISTS idx_bugs_knowledge_vector ON bugs_knowledge 
USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

CREATE INDEX IF NOT EXISTS idx_code_knowledge_vector ON code_knowledge 
USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- 6. Índices adicionais
CREATE INDEX IF NOT EXISTS idx_knowledge_embeddings_category ON knowledge_embeddings(category);
CREATE INDEX IF NOT EXISTS idx_bugs_knowledge_language ON bugs_knowledge(language);
CREATE INDEX IF NOT EXISTS idx_code_knowledge_language ON code_knowledge(language);
