-- GIOM VECTOR DATABASE - pgvector Schema
-- Execute no Supabase SQL Editor

-- 1. Ativar extensão pgvector
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Tabela de embeddings profissionais
CREATE TABLE IF NOT EXISTS knowledge_embeddings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  embedding VECTOR(384), -- HuggingFace dimensions (grátis)
  source TEXT,
  category TEXT,
  language TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabela de bugs e soluções
CREATE TABLE IF NOT EXISTS bugs_knowledge (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  error_message TEXT NOT NULL,
  stack_trace TEXT,
  solution TEXT NOT NULL,
  language TEXT,
  framework TEXT,
  embedding VECTOR(384), -- HuggingFace dimensions
  confidence FLOAT DEFAULT 0.0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Tabela de código aprendido
CREATE TABLE IF NOT EXISTS code_knowledge (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repo_url TEXT,
  file_path TEXT,
  content TEXT NOT NULL,
  language TEXT,
  functions JSONB, -- Lista de funções extraídas
  patterns JSONB, -- Padrões identificados
  embedding VECTOR(384), -- HuggingFace dimensions
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Índices para performance
CREATE INDEX IF NOT EXISTS idx_knowledge_embeddings_vector ON knowledge_embeddings 
USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

CREATE INDEX IF NOT EXISTS idx_bugs_knowledge_vector ON bugs_knowledge 
USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

CREATE INDEX IF NOT EXISTS idx_code_knowledge_vector ON code_knowledge 
USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- 6. Índices adicionais
CREATE INDEX IF NOT EXISTS idx_knowledge_embeddings_category ON knowledge_embeddings(category);
CREATE INDEX IF NOT EXISTS idx_bugs_knowledge_language ON bugs_knowledge(language);
CREATE INDEX IF NOT EXISTS idx_code_knowledge_language ON code_knowledge(language);

-- 7. Habilitar RLS
ALTER TABLE knowledge_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE bugs_knowledge ENABLE ROW LEVEL SECURITY;
ALTER TABLE code_knowledge ENABLE ROW LEVEL SECURITY;

-- 8. Políticas RLS
CREATE POLICY "Enable read access for all users" ON knowledge_embeddings
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users" ON knowledge_embeddings
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable read access for all users" ON bugs_knowledge
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users" ON bugs_knowledge
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable read access for all users" ON code_knowledge
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users" ON code_knowledge
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 9. Função de busca semântica
CREATE OR REPLACE FUNCTION search_knowledge(
  query_embedding VECTOR(384),
  match_threshold FLOAT DEFAULT 0.3,
  match_count INT DEFAULT 5
)
RETURNS TABLE(
  id BIGINT,
  content TEXT,
  source TEXT,
  category TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    ke.id,
    ke.content,
    ke.source,
    ke.category,
    1 - (ke.embedding <=> query_embedding) AS similarity
  FROM knowledge_embeddings ke
  WHERE 1 - (ke.embedding <=> query_embedding) > match_threshold
  ORDER BY ke.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- 10. Função de busca de bugs
CREATE OR REPLACE FUNCTION search_bugs(
  query_embedding VECTOR(384),
  language_param TEXT DEFAULT NULL,
  match_threshold FLOAT DEFAULT 0.3,
  match_count INT DEFAULT 3
)
RETURNS TABLE(
  id BIGINT,
  error_message TEXT,
  solution TEXT,
  language TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    bk.id,
    bk.error_message,
    bk.solution,
    bk.language,
    1 - (bk.embedding <=> query_embedding) AS similarity
  FROM bugs_knowledge bk
  WHERE 1 - (bk.embedding <=> query_embedding) > match_threshold
    AND (language_param IS NULL OR bk.language = language_param)
  ORDER BY bk.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- 11. Trigger para atualizar timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_knowledge_embeddings_updated_at 
BEFORE UPDATE ON knowledge_embeddings
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_bugs_knowledge_updated_at 
BEFORE UPDATE ON bugs_knowledge
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_code_knowledge_updated_at 
BEFORE UPDATE ON code_knowledge
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

COMMIT;
