-- GIOM DATABASE SCHEMA - Supabase SQL
-- Execute este SQL no painel do Supabase

-- Tabela de conversas
CREATE TABLE IF NOT EXISTS conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  user_message TEXT NOT NULL,
  ai_response TEXT NOT NULL,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de perfis de usuário
CREATE TABLE IF NOT EXISTS user_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT UNIQUE NOT NULL,
  preferences JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de conhecimento (RAG)
CREATE TABLE IF NOT EXISTS knowledge_base (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  source TEXT,
  category TEXT,
  embedding VECTOR(1536), -- Para OpenAI embeddings
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de aprendizado
CREATE TABLE IF NOT EXISTS learning_patterns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  pattern_type TEXT NOT NULL, -- 'style', 'topic', 'preference'
  pattern_data JSONB NOT NULL,
  confidence FLOAT DEFAULT 0.0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_conversations_user_id ON conversations(user_id);
CREATE INDEX IF NOT EXISTS idx_conversations_created_at ON conversations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_profiles_user_id ON user_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_base_category ON knowledge_base(category);
CREATE INDEX IF NOT EXISTS idx_learning_patterns_user_id ON learning_patterns(user_id);

-- Habilitar RLS (Row Level Security)
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_base ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_patterns ENABLE ROW LEVEL SECURITY;

-- Políticas RLS
-- Conversas: usuários só veem suas próprias conversas
CREATE POLICY "Users can view own conversations" ON conversations
  FOR SELECT USING (auth.uid()::text = user_id);

CREATE POLICY "Users can insert own conversations" ON conversations
  FOR INSERT WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Users can update own conversations" ON conversations
  FOR UPDATE USING (auth.uid()::text = user_id);

-- Perfis: usuários só veem/criam seu próprio perfil
CREATE POLICY "Users can view own profile" ON user_profiles
  FOR SELECT USING (auth.uid()::text = user_id);

CREATE POLICY "Users can upsert own profile" ON user_profiles
  FOR ALL USING (auth.uid()::text = user_id);

-- Knowledge base: leitura pública, escrita restrita
CREATE POLICY "Enable read access for all users" ON knowledge_base
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users" ON knowledge_base
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Learning patterns: usuários só veem seus padrões
CREATE POLICY "Users can view own patterns" ON learning_patterns
  FOR SELECT USING (auth.uid()::text = user_id);

CREATE POLICY "Users can insert own patterns" ON learning_patterns
  FOR INSERT WITH CHECK (auth.uid()::text = user_id);

-- Função para atualizar timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers para atualizar timestamp
CREATE TRIGGER update_conversations_updated_at BEFORE UPDATE ON conversations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_profiles_updated_at BEFORE UPDATE ON user_profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_knowledge_base_updated_at BEFORE UPDATE ON knowledge_base
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Inserir perfil inicial para usuário padrão
INSERT INTO user_profiles (user_id, preferences)
VALUES ('default_user', '{"style": "natural", "name": "Usuário", "level": "beginner", "assistantProfile": "adaptive_teacher", "activeModules": ["developer"], "bibleStudyModules": []}')
ON CONFLICT (user_id) DO NOTHING;

-- Inserir conhecimento base
INSERT INTO knowledge_base (title, content, source, category, metadata)
VALUES 
  ('GIOM Identity', 'Eu sou GIOM, uma inteligência artificial avançada criada em 17/03/2026 por Gabriel Lima de Souza. Minha missão é ajudar desenvolvedores com código, debugging e aprendizado.', 'system', 'identity', '{"type": "core", "priority": "high"}'),
  ('JavaScript Basics', 'JavaScript é uma linguagem de programação usada para criar interatividade em páginas web. É executada no navegador e permite manipular DOM, fazer requisições HTTP e criar aplicações dinâmicas.', 'internal', 'programming', '{"language": "javascript", "level": "basic"}'),
  ('Node.js', 'Node.js é um runtime JavaScript que permite executar JavaScript no servidor. Criado com base no V8 Engine do Chrome, é usado para construir APIs e aplicações backend.', 'internal', 'programming', '{"language": "javascript", "level": "intermediate"}')
ON CONFLICT DO NOTHING;

COMMIT;
