export { registerEnterpriseAskRoutes } from "./enterpriseAskRoutesRuntime.js"
export { registerEnterpriseAdminRoutes } from "./enterpriseAdminRoutesRuntime.js"
export { registerEnterpriseBibleRoutes } from "./enterpriseBibleRoutesRuntime.js"
export { registerEnterpriseCompatRoutes } from "./enterpriseCompatRoutesRuntime.js"
export { registerEnterpriseFeedbackRoutes } from "./enterpriseFeedbackRoutesRuntime.js"
export { registerEnterpriseKnowledgeRoutes } from "./enterpriseKnowledgeRoutesRuntime.js"
export { registerEnterpriseMediaRoutes } from "./enterpriseMediaRoutesRuntime.js"
export { registerEnterprisePublicRoutes } from "./enterprisePublicRoutesRuntime.js"
export { registerEnterpriseQualityRoutes } from "./enterpriseQualityRoutesRuntime.js"
export { registerEnterpriseResearchRoutes } from "./enterpriseResearchRoutesRuntime.js"
// @ts-expect-error JS-only runtime module is loaded intentionally from source.
export { registerEnterpriseVoiceRoutes } from "../src/enterpriseVoiceRoutesRuntime.js"
