// EXECUTAR SCHEMA SUPABASE AUTOMATICAMENTE
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.SUPABASE_URL
const supabaseKey = process.env.SUPABASE_ANON_KEY || process.env.SUPABASE_KEY

if (!supabaseUrl || !supabaseKey) {
  console.error('❌ SUPABASE_URL / SUPABASE_ANON_KEY não configurados no ambiente.')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseKey)

// Schema SQL completo
const schemaSQL = `
-- GROOT DATABASE SCHEMA - Supabase SQL

-- Tabela de conversas
CREATE TABLE IF NOT EXISTS conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  user_message TEXT NOT NULL,
  ai_response TEXT NOT NULL,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de perfis de usuário
CREATE TABLE IF NOT EXISTS user_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT UNIQUE NOT NULL,
  preferences JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de conhecimento (RAG)
CREATE TABLE IF NOT EXISTS knowledge_base (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  source TEXT,
  category TEXT,
  embedding VECTOR(1536),
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de aprendizado
CREATE TABLE IF NOT EXISTS learning_patterns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  pattern_type TEXT NOT NULL,
  pattern_data JSONB NOT NULL,
  confidence FLOAT DEFAULT 0.0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_conversations_user_id ON conversations(user_id);
CREATE INDEX IF NOT EXISTS idx_conversations_created_at ON conversations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_profiles_user_id ON user_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_base_category ON knowledge_base(category);
CREATE INDEX IF NOT EXISTS idx_learning_patterns_user_id ON learning_patterns(user_id);

-- Habilitar RLS (Row Level Security)
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_base ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_patterns ENABLE ROW LEVEL SECURITY;

-- Políticas RLS
CREATE POLICY "Users can view own conversations" ON conversations
  FOR SELECT USING (auth.uid()::text = user_id);

CREATE POLICY "Users can insert own conversations" ON conversations
  FOR INSERT WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Users can update own conversations" ON conversations
  FOR UPDATE USING (auth.uid()::text = user_id);

CREATE POLICY "Users can view own profile" ON user_profiles
  FOR SELECT USING (auth.uid()::text = user_id);

CREATE POLICY "Users can upsert own profile" ON user_profiles
  FOR ALL USING (auth.uid()::text = user_id);

CREATE POLICY "Enable read access for all users" ON knowledge_base
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users" ON knowledge_base
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can view own patterns" ON learning_patterns
  FOR SELECT USING (auth.uid()::text = user_id);

CREATE POLICY "Users can insert own patterns" ON learning_patterns
  FOR INSERT WITH CHECK (auth.uid()::text = user_id);

-- Função para atualizar timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers para atualizar timestamp
CREATE TRIGGER update_conversations_updated_at BEFORE UPDATE ON conversations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_profiles_updated_at BEFORE UPDATE ON user_profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_knowledge_base_updated_at BEFORE UPDATE ON knowledge_base
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Inserir perfil inicial para usuário padrão
INSERT INTO user_profiles (user_id, preferences)
VALUES ('default_user', '{"style": "natural", "name": "Usuário", "level": "beginner"}')
ON CONFLICT (user_id) DO NOTHING;

-- Inserir conhecimento base
INSERT INTO knowledge_base (title, content, source, category, metadata)
VALUES 
  ('GROOT Identity', 'Eu sou GROOT, uma inteligência artificial avançada criada em 17/03/2026 por Gabriel Lima de Souza. Minha missão é ajudar desenvolvedores com código, debugging e aprendizado.', 'system', 'identity', '{"type": "core", "priority": "high"}'),
  ('JavaScript Basics', 'JavaScript é uma linguagem de programação usada para criar interatividade em páginas web. É executada no navegador e permite manipular DOM, fazer requisições HTTP e criar aplicações dinâmicas.', 'internal', 'programming', '{"language": "javascript", "level": "basic"}'),
  ('Node.js', 'Node.js é um runtime JavaScript que permite executar JavaScript no servidor. Criado com base no V8 Engine do Chrome, é usado para construir APIs e aplicações backend.', 'internal', 'programming', '{"language": "javascript", "level": "intermediate"}')
ON CONFLICT DO NOTHING;

COMMIT;
`

async function executeSchema() {
  try {
    console.log('🔍 Executando schema do Supabase...')
    
    // Nota: Supabase não permite executar múltiplos comandos SQL via API
    // Precisa ser feito manualmente no painel
    
    console.log('⚠️ ATENÇÃO: O schema precisa ser executado manualmente!')
    console.log('📋 Acesse: https://supabase.com/dashboard/project/nyvljbcrfletvxqwprgb/sql')
    console.log('📝 Cole o conteúdo do arquivo: database/supabase-schema.sql')
    console.log('🚀 Execute tudo de uma vez')
    
    // Testar se tabelas existem
    const { data, error } = await supabase
      .from('conversations')
      .select('count')
      .limit(1)
    
    if (error) {
      console.error('❌ Schema ainda não foi executado:', error.message)
      console.log('📋 Execute o schema manualmente no painel do Supabase!')
    } else {
      console.log('✅ Schema executado com sucesso!')
      console.log('📊 Total conversas:', data[0]?.count || 0)
    }
    
  } catch (err) {
    console.error('❌ Erro ao executar schema:', err.message)
  }
}

executeSchema()
